import { useCallback, useEffect, useState } from "react";
import { FolderTree, Plus, RefreshCw, ToggleLeft, ToggleRight } from "lucide-react";
import PageContainer from "@/components/layout/PageContainer";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Textarea from "@/components/ui/Textarea";
import Modal from "@/components/ui/Modal";
import EmptyState from "@/components/ui/EmptyState";
import { supabase } from "@/libs/supabase";
import { getSafeErrorMessage } from "@/libs/errors";

type Category={id:string;name:string;slug:string;description:string|null;parent_id:string|null;sort_order:number;is_active:boolean;created_at:string};
const slugify=(v:string)=>v.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
export default function Categories(){const [rows,setRows]=useState<Category[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [open,setOpen]=useState(false);const [name,setName]=useState("");const [description,setDescription]=useState("");const [sortOrder,setSortOrder]=useState("0");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const {data,error:e}=await supabase.from("categories").select("id,name,slug,description,parent_id,sort_order,is_active,created_at").order("sort_order",{ascending:true}).order("name",{ascending:true});if(e)throw e;setRows((data??[]) as Category[]);}catch(e){setError(getSafeErrorMessage(e));}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function save(){const trimmed=name.trim();if(trimmed.length<2){setError("Category name must contain at least 2 characters.");return;}try{setSaving(true);setError("");const {error:e}=await supabase.from("categories").insert({name:trimmed,slug:slugify(trimmed),description:description.trim()||null,sort_order:Number(sortOrder)||0,is_active:true});if(e)throw e;setOpen(false);setName("");setDescription("");setSortOrder("0");await load();}catch(e){setError(getSafeErrorMessage(e));}finally{setSaving(false);}}
 async function toggle(row:Category){try{setError("");const {error:e}=await supabase.from("categories").update({is_active:!row.is_active}).eq("id",row.id);if(e)throw e;await load();}catch(e){setError(getSafeErrorMessage(e));}}
 return <PageContainer size="full"><div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-brand-600">Marketplace taxonomy</p><h1 className="mt-1 text-2xl font-bold text-ink-950">Categories</h1><p className="mt-1 text-sm text-slate-600">Manage the categories that business owners use when publishing products.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="h-4 w-4"/>Refresh</Button><Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Add category</Button></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="rounded-2xl border border-slate-200 bg-white shadow-sm">{!loading&&rows.length===0?<EmptyState title="No categories yet" description="Create the first marketplace category. Nothing is shown until a real category exists." icon={<FolderTree className="h-6 w-6"/>}/>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b border-slate-200 text-left"><th className="px-5 py-3 font-semibold text-slate-600">Category</th><th className="px-5 py-3 font-semibold text-slate-600">Slug</th><th className="px-5 py-3 font-semibold text-slate-600">Order</th><th className="px-5 py-3 font-semibold text-slate-600">Status</th><th className="px-5 py-3 text-right font-semibold text-slate-600">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-semibold text-ink-950">{r.name}</p><p className="text-xs text-slate-500">{r.description||"No description"}</p></td><td className="px-5 py-4 text-slate-600">{r.slug}</td><td className="px-5 py-4 text-slate-600">{r.sort_order}</td><td className="px-5 py-4">{r.is_active?<span className="text-emerald-600">Active</span>:<span className="text-slate-500">Inactive</span>}</td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" onClick={()=>void toggle(r)}>{r.is_active?<ToggleRight className="h-4 w-4"/>:<ToggleLeft className="h-4 w-4"/>}{r.is_active?"Deactivate":"Activate"}</Button></td></tr>)}</tbody></table></div>}</div><Modal open={open} onClose={()=>setOpen(false)} title="Create category"><div className="space-y-4"><Input label="Category name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Fashion"/><Textarea label="Description" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional category description"/><Input label="Sort order" type="number" min="0" value={sortOrder} onChange={e=>setSortOrder(e.target.value)}/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={saving} onClick={()=>void save()}>Create category</Button></div></div></Modal></div></PageContainer>}
