import { useCallback, useEffect, useMemo, useState } from "react";
import { Bike, CheckCircle2, Eye, RefreshCw, Search, UserCheck, UserX } from "lucide-react";
import PageContainer from "@/components/layout/PageContainer";
import AdminFilters from "@/components/admin/AdminFilters";
import AdminTable, { type AdminTableColumn, type AdminTableRowAction } from "@/components/admin/AdminTable";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import EmptyState from "@/components/ui/EmptyState";
import { formatDate } from "@/libs/format";
import { getSafeErrorMessage } from "@/libs/errors";
import { supabase } from "@/libs/supabase";
import { setRiderActive, setRiderVerification } from "@/services/admin";

type Rider = { id:string; user_id:string; full_name:string; phone:string; operating_city:string|null; operating_state:string|null; operating_area:string|null; vehicle_type:string; verification_status:string; availability_status:string; is_active:boolean; is_online:boolean; created_at:string };
const verificationOptions=[{value:"",label:"All verification statuses"},{value:"pending",label:"Pending"},{value:"under_review",label:"Under review"},{value:"verified",label:"Verified"},{value:"rejected",label:"Rejected"},{value:"suspended",label:"Suspended"}];
const availabilityOptions=[{value:"",label:"All availability"},{value:"available",label:"Available"},{value:"busy",label:"Busy"},{value:"offline",label:"Offline"}];
function label(value:string|null|undefined){return String(value??"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())||"Unknown";}
function variant(status:string){return status==="verified"||status==="available"?"success" as const:status==="pending"||status==="under_review"||status==="busy"?"warning" as const:status==="rejected"||status==="suspended"?"danger" as const:"default" as const;}
export default function Riders(){
 const [riders,setRiders]=useState<Rider[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [verification,setVerification]=useState(""); const [availability,setAvailability]=useState(""); const [saving,setSaving]=useState<string|null>(null);
 const load=useCallback(async(refresh=false)=>{try{refresh?setRefreshing(true):setLoading(true);setError("");const {data,error}=await supabase.from("riders").select("id,user_id,full_name,phone,operating_city,operating_state,operating_area,vehicle_type,verification_status,availability_status,is_active,is_online,created_at").order("created_at",{ascending:false});if(error)throw error;setRiders((data??[]) as Rider[]);}catch(e){setError(getSafeErrorMessage(e));}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return riders.filter(r=>(!q||[r.full_name,r.phone,r.operating_city,r.operating_state,r.operating_area,r.vehicle_type].filter(Boolean).join(" ").toLowerCase().includes(q))&&(!verification||r.verification_status===verification)&&(!availability||r.availability_status===availability));},[riders,search,verification,availability]);
 async function verify(id:string,status:string){try{setSaving(id);setError("");await setRiderVerification(id,status);await load(true);}catch(e){setError(getSafeErrorMessage(e));}finally{setSaving(null);}}
 async function active(id:string,value:boolean){try{setSaving(id);setError("");await setRiderActive(id,value);await load(true);}catch(e){setError(getSafeErrorMessage(e));}finally{setSaving(null);}}
 const columns:AdminTableColumn<Rider>[]=[
 {id:"rider",header:"Rider",accessor:"full_name",sortable:true,render:(_,r)=><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Bike className="h-5 w-5"/></div><div><p className="font-medium text-ink-950">{r.full_name}</p><p className="text-xs text-slate-500">{r.phone}</p></div></div>},
 {id:"vehicle",header:"Vehicle",accessor:"vehicle_type",sortable:true,render:v=><span className="text-sm text-slate-700">{label(v)}</span>},
 {id:"location",header:"Operating area",accessor:"operating_city",sortable:true,render:(_,r)=><span className="text-sm text-slate-700">{[r.operating_area,r.operating_city,r.operating_state].filter(Boolean).join(", ")||"—"}</span>},
 {id:"verification",header:"Verification",accessor:"verification_status",sortable:true,render:v=><Badge variant={variant(v)}>{label(v)}</Badge>},
 {id:"presence",header:"Availability",accessor:"availability_status",sortable:true,render:(_,r)=><Badge variant={r.is_online&&r.is_active?variant(r.availability_status):"default"}>{r.is_online&&r.is_active?label(r.availability_status):"Offline"}</Badge>},
 {id:"active",header:"Account",accessor:"is_active",render:v=><Badge variant={v?"success":"danger"}>{v?"Active":"Inactive"}</Badge>},
 {id:"actions",header:"Actions",align:"right",render:(_,r)=><div className="flex justify-end"><Button size="sm" variant={r.verification_status==="verified"?"outline":"default"} loading={saving===r.id} onClick={()=>void verify(r.id,r.verification_status==="verified"?"under_review":"verified")}>{r.verification_status==="verified"?<UserX className="h-4 w-4"/>:<UserCheck className="h-4 w-4"/>}{r.verification_status==="verified"?"Review":"Verify"}</Button></div>},
 {id:"created",header:"Joined",accessor:"created_at",sortable:true,render:v=><span className="text-sm text-slate-600">{formatDate(v)}</span>},
 ];
 const actions=(r:Rider):AdminTableRowAction[]=>[{id:"verify",label:r.verification_status==="verified"?"Set under review":"Verify rider",icon:r.verification_status==="verified"?UserX:UserCheck,onClick:()=>void verify(r.id,r.verification_status==="verified"?"under_review":"verified")},{id:"active",label:r.is_active?"Deactivate rider":"Activate rider",icon:r.is_active?UserX:UserCheck,onClick:()=>void active(r.id,!r.is_active),danger:r.is_active},{id:"view",label:"Open rider profile",icon:Eye,onClick:()=>window.location.assign(`/rider/profile?userId=${r.user_id}`)}];
 return <PageContainer size="full"><div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-brand-600">Verification and operations</p><h1 className="mt-1 text-2xl font-bold text-ink-950">Riders</h1><p className="mt-1 text-sm text-slate-600">Review real rider applications, verification status, availability and account access.</p></div><Button variant="outline" onClick={()=>void load(true)} loading={refreshing}><RefreshCw className="h-4 w-4"/>Refresh</Button></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<AdminFilters><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search riders..." className="h-10 w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm text-slate-900 outline-none focus:border-brand-400 focus:ring-2 focus:ring-brand-100"/></div><select value={verification} onChange={e=>setVerification(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700">{verificationOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><select value={availability} onChange={e=>setAvailability(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700">{availabilityOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></AdminFilters><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total riders" value={riders.length}/><Stat label="Pending verification" value={riders.filter(r=>["pending","under_review"].includes(r.verification_status)).length}/><Stat label="Verified" value={riders.filter(r=>r.verification_status==="verified").length}/><Stat label="Online" value={riders.filter(r=>r.is_online&&r.is_active).length}/></div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><AdminTable columns={columns} data={filtered} rowKey={r=>r.id} getRowActions={actions} loading={loading} emptyTitle="No riders found" emptyDescription="Rider applications and accounts will appear here when they exist in the database." pagination pageSize={10} stickyHeader striped/></div></div></PageContainer>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-ink-950">{value.toLocaleString()}</p></div>}
