import { useCallback, useEffect, useState } from "react";
import { CreditCard, Database, Save, Settings as SettingsIcon, ShieldCheck } from "lucide-react";
import PageContainer from "@/components/layout/PageContainer";
import Button from "@/components/ui/Button";
import Input from "@/components/ui/Input";
import Badge from "@/components/ui/Badge";
import EmptyState from "@/components/ui/EmptyState";
import ErrorState from "@/components/ui/ErrorState";
import { supabase } from "@/libs/supabase";
import { getSafeErrorMessage } from "@/libs/errors";
import { formatNaira } from "@/libs/format";

type PlatformSettings = { id: string; platform_fee_rate: number; currency: string; is_active: boolean; updated_at: string };

export default function Settings(){
 const [settings,setSettings]=useState<PlatformSettings|null>(null); const [rate,setRate]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const {data,error:queryError}=await supabase.from("platform_settings").select("id,platform_fee_rate,currency,is_active,updated_at").eq("is_active",true).maybeSingle();if(queryError)throw queryError;setSettings(data as PlatformSettings|null);setRate(data?String(data.platform_fee_rate):"");}catch(e){setError(getSafeErrorMessage(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function save(){const value=Number(rate);if(!Number.isFinite(value)||value<0||value>100){setError("Enter a platform fee between 0 and 100 percent.");return;}if(!settings){setError("Platform settings could not be found.");return;}try{setSaving(true);setError("");setSaved(false);const {data,error:updateError}=await supabase.from("platform_settings").update({platform_fee_rate:value}).eq("id",settings.id).select("id,platform_fee_rate,currency,is_active,updated_at").single();if(updateError)throw updateError;setSettings(data as PlatformSettings);setRate(String(data.platform_fee_rate));setSaved(true);}catch(e){setError(getSafeErrorMessage(e));}finally{setSaving(false);}}
 if(loading)return <PageContainer><div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-600">Loading platform settings...</div></PageContainer>;
 if(error&&!settings)return <PageContainer><ErrorState message={error} onAction={()=>void load()}/></PageContainer>;
 return <PageContainer size="full"><div className="space-y-6"><div><p className="text-sm font-medium text-brand-600">Platform configuration</p><h1 className="mt-1 text-2xl font-bold text-ink-950">Settings</h1><p className="mt-1 text-sm text-slate-600">Only settings that exist in the database are shown here. There are no frontend-only configuration values.</p></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{saved&&<Badge variant="success">Settings saved</Badge>}<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><SettingsIcon className="h-5 w-5"/></div><div><h2 className="font-semibold text-ink-950">Active platform settings</h2><p className="text-sm text-slate-600">Server-authoritative values used by checkout and financial logic.</p></div></div>{settings?<div className="mt-6 grid gap-6 md:grid-cols-2"><div><Input label="Platform commission (%)" type="number" min="0" max="100" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} helperText="This value is stored in platform_settings and used by the checkout backend."/></div><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-brand-600"><CreditCard className="h-5 w-5"/><span className="font-semibold">Current financial model</span></div><p className="mt-3 text-sm text-slate-600">Currency: <strong className="text-ink-950">{settings.currency}</strong></p><p className="mt-1 text-sm text-slate-600">Commission: <strong className="text-ink-950">{Number(settings.platform_fee_rate).toFixed(2)}%</strong></p><p className="mt-1 text-sm text-slate-600">Example on ₦20,000: <strong className="text-ink-950">{formatNaira(20000*Number(settings.platform_fee_rate)/100)}</strong></p><p className="mt-3 text-xs text-slate-400">Last updated: {new Date(settings.updated_at).toLocaleString("en-NG")}</p></div></div>:<EmptyState title="No active platform settings" description="Create an active platform settings record in Supabase before configuring the marketplace."/>}<div className="mt-6 flex justify-end"><Button onClick={()=>void save()} loading={saving} disabled={!settings}><Save className="h-4 w-4"/>Save changes</Button></div></section><section className="grid gap-5 md:grid-cols-2"><InfoCard icon={ShieldCheck} title="Security" text="Administrative role assignment, business verification and rider verification are enforced by protected database workflows."/><InfoCard icon={Database} title="Data source" text="Dashboards and operational screens read live Supabase records instead of bundled demo data."/></section></div></PageContainer>;
}
function InfoCard({icon:Icon,title,text}:{icon:typeof ShieldCheck;title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><Icon className="h-5 w-5"/></div><h3 className="mt-4 font-semibold text-ink-950">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div>}
