import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Wallet } from "lucide-react";
import PageContainer from "@/components/layout/PageContainer";
import Button from "@/components/ui/Button";
import Badge from "@/components/ui/Badge";
import EmptyState from "@/components/ui/EmptyState";
import ErrorState from "@/components/ui/ErrorState";
import { supabase } from "@/libs/supabase";
import { getSafeErrorMessage } from "@/libs/errors";
import { formatNaira } from "@/libs/format";
type WalletRow={id:string;customer_id:string;available_balance:number;pending_balance:number;currency:string;is_active:boolean;updated_at:string};type Profile={id:string;full_name:string|null;phone:string|null};
export default function Wallets(){const [rows,setRows]=useState<WalletRow[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=useCallback(async()=>{try{setLoading(true);setError("");const {data,error:e}=await supabase.from("customer_wallets").select("id,customer_id,available_balance,pending_balance,currency,is_active,updated_at").order("updated_at",{ascending:false}).limit(200);if(e)throw e;const wallets=(data??[]) as WalletRow[];setRows(wallets);const ids=[...new Set(wallets.map(w=>w.customer_id))];if(ids.length){const {data:ps,error:pe}=await supabase.from("profiles").select("id,full_name,phone").in("id",ids);if(pe)throw pe;setProfiles(Object.fromEntries(((ps??[]) as Profile[]).map(p=>[p.id,p])));}}catch(e){setError(getSafeErrorMessage(e));}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);return <PageContainer size="full"><div className="space-y-6"><div className="flex justify-between gap-4"><div><p className="text-sm font-medium text-brand-600">Customer finance</p><h1 className="mt-1 text-2xl font-bold text-ink-950">Wallets</h1><p className="mt-1 text-sm text-slate-600">Live customer wallet balances and account status.</p></div><Button variant="outline" onClick={()=>void load()} loading={loading}><RefreshCw className="h-4 w-4"/>Refresh</Button></div>{error&&!rows.length?<ErrorState message={error} onAction={()=>void load()}/>:<div className="rounded-2xl border border-slate-200 bg-white shadow-sm">{!loading&&!rows.length?<EmptyState title="No customer wallets" description="Wallets appear automatically when customer wallet accounts are created." icon={<Wallet className="h-6 w-6"/>}/>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b border-slate-200 text-left"><th className="px-5 py-3 font-semibold text-slate-600">Customer</th><th className="px-5 py-3 text-right font-semibold text-slate-600">Available</th><th className="px-5 py-3 text-right font-semibold text-slate-600">Pending</th><th className="px-5 py-3 font-semibold text-slate-600">Status</th></tr></thead><tbody>{rows.map(w=><tr key={w.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4"><p className="font-medium text-ink-950">{profiles[w.customer_id]?.full_name||"Customer"}</p><p className="text-xs text-slate-500">{profiles[w.customer_id]?.phone||""}</p></td><td className="px-5 py-4 text-right font-semibold text-ink-950">{formatNaira(Number(w.available_balance))}</td><td className="px-5 py-4 text-right text-slate-700">{formatNaira(Number(w.pending_balance))}</td><td className="px-5 py-4"><Badge variant={w.is_active?"success":"default"}>{w.is_active?"Active":"Inactive"}</Badge></td></tr>)}</tbody></table></div>}</div>}</div></PageContainer>}
